### ISSUE TITLE
project kotlin multiplatform : error failed to resolve tech.apter.junit5.jupiter.robolectric-extension-gradle-plugin 0.8.0

### ISSUE THREAD

**Issue by fpitpit** [apter-tech/junit5-robolectric-extension#95]
In a Kotlin mutliplatform I try to add plugin for android module using version catalog but build failed to resolve the plugin

version catalog : 
```
[versions]
junit5-robolectric = "0.8.0"
[plugins]
junit5-robolectric = { id = "tech.apter.junit5.jupiter.robolectric-extension-gradle-plugin", version.ref = "junit5-robolectric" } 
```

build.gradle.kts (root project)

```
plugins {
    // this is necessary to avoid the plugins to be loaded multiple times
    // in each subproject's classloader
    alias(libs.plugins.androidApplication) apply false
    alias(libs.plugins.androidLibrary) apply false
    alias(libs.plugins.jetbrainsCompose) apply false
    alias(libs.plugins.compose.compiler) apply false
    alias(libs.plugins.kotlinMultiplatform) apply false
    alias(libs.plugins.junit5.robolectric) apply  false
}
```

build.gradle.kts (composeApp/android)

```
android {
    apply(plugin = libs.plugins.junit5.robolectric.get().pluginId)
    ....
}
```
I've got error : **`Failed to resolve: tech.apter.junit5.jupiter:robolectric-extension:0.8.0`**

I've same error on a classic project android

**all tests failed now on kotlin multiplatform : if I reuse junit4 and run with robolectric test runner it works but not with your plugin**

**Comment by fpitpit** [comment]
Ah it's ok when i add this 

androidUnitTest.dependencies {
          implementation(kotlin("test-junit5"))
}

**Comment by fpitpit** [comment]
in kotlin multiplatform all tests failed :
`Caused by: org.junit.runners.model.InvalidTestClassError: Invalid test class '.........UsingContext':
  1. No runnable methods
	at org.junit.runners.ParentRunner.validate(ParentRunner.java:525)
	at org.junit.runners.ParentRunner.<init>(ParentRunner.java:92)
	at org.junit.runners.BlockJUnit4ClassRunner.<init>(BlockJUnit4ClassRunner.java:74)
	at org.robolectric.internal.SandboxTestRunner.<init>(SandboxTestRunner.java:77)
	at org.robolectric.RobolectricTestRunner.<init>(RobolectricTestRunner.java:105)
	at tech.apter.junit.jupiter.robolectric.internal.JUnit5RobolectricTestRunner.<init>(JUnit5RobolectricTestRunner.kt:27)
	at tech.apter.junit.jupiter.robolectric.internal.JUnit5RobolectricTestRunner.<init>(JUnit5RobolectricTestRunner.kt:21)
	at tech.apter.junit.jupiter.robolectric.internal.JUnit5RobolectricTestRunnerHelper.createTestEnvironmentForClass(JUnit5RobolectricTestRunnerHelper.kt:37)
	at tech.apter.junit.jupiter.robolectric.internal.JUnit5RobolectricTestRunnerHelper.<init>(JUnit5RobolectricTestRunnerHelper.kt:21)
	at tech.apter.junit.jupiter.robolectric.internal.JUnit5RobolectricTestRunnerHelper.<init>(JUnit5RobolectricTestRunnerHelper.kt)
	at tech.apter.junit.jupiter.robolectric.internal.JUnit5RobolectricTestRunnerHelper$Companion.getInstance$robolectric_extension(JUnit5RobolectricTestRunnerHelper.kt:99)
	at tech.apter.junit.jupiter.robolectric.internal.RobolectricClassLoaderFactoryKt.robolectricClassLoaderFactory(RobolectricClassLoaderFactory.kt:17)
	at tech.apter.junit.jupiter.robolectric.internal.JUnit5RobolectricTestRunnerHelper$Companion$setUp$2.invoke(JUnit5RobolectricTestRunnerHelper.kt:84)
	at tech.apter.junit.jupiter.robolectric.internal.JUnit5RobolectricTestRunnerHelper$Companion$setUp$2.invoke(JUnit5RobolectricTestRunnerHelper.kt:84)
	at tech.apter.junit.jupiter.robolectric.internal.RobolectricTestClassClassLoader.loadClass(RobolectricTestClassClassLoader.kt:29)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:495)
	at java.base/java.lang.Class.forName(Class.java:474)
	at org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor.loadClass(JUnitPlatformTestClassProcessor.java:173)
	at org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor.access$100(JUnitPlatformTestClassProcessor.java:62)
	at org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor$CollectAllTestClassesExecutor.execute(JUnitPlatformTestClassProcessor.java:109)
	at org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor$CollectAllTestClassesExecutor.execute(JUnitPlatformTestClassProcessor.java:99)
	at org.gradle.api.internal.tasks.testing.junit.AbstractJUnitTestClassProcessor.processTestClass(AbstractJUnitTestClassProcessor.java:54)
	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:53)`

**Comment by fpitpit** [comment]
ok the plugin believes that my actual class is a Test so it failed (Gradle Test Executor 1)

To fix it I must exclude my actual class in test block in my gradle file : 

`tasks.withType<Test>().configureEach {
    useJUnitPlatform()
    exclude("**/UsingContext.class")
}`

**Comment by warnyul** [comment]
Why your `UsingContext` class is annotated with `@ExtendWith(RobolectricExtension::class)` if it is not a test class?

**Comment by mannodermaus** [comment]
I'm seeing this too, but with a pure-Android project. It seems like version `0.8.0` of the Gradle plugin exists on the [Gradle Plugin Portal](https://plugins.gradle.org/plugin/tech.apter.junit5.jupiter.robolectric-extension-gradle-plugin), however the extension itself has no such version available on [Maven Central](https://mvnrepository.com/artifact/tech.apter.junit5.jupiter/robolectric-extension). Is the extension deployed to a different repository with the latest version, or did something in the deployment go awry?

<img width="592" alt="Screenshot 2024-10-23 at 11 08 52" src="https://github.com/user-attachments/assets/ed0422e8-05e3-4509-902e-419c1509b076">

**Comment by warnyul** [comment]
@fpitpit Could you confirm this is solved your issue? Am I close this issue?

**Comment by mannodermaus** [comment]
I can confirm that resolving version 0.8.0 of the plugin now also fetches the extension without issue. Thank you for checking this!

<img width="420" alt="Screenshot 2024-10-23 at 17 54 49" src="https://github.com/user-attachments/assets/ac61b3ca-80a6-4624-85a6-3a2df9d034ba">

**Comment by fpitpit** [comment]
No I can't get 0.8.0. only works with 0.7.0
